title: Approvers
description: Responsible for approving changes that have a significant impact on AMP's behavior or significant new features as described in the feature and bug fix process. Facilitator: @dvoytenko
facilitator:
  login: dvoytenko
  name:
members:
  - login: dvoytenko
    name:
